### ISSUE TITLE
[Question] What does the name "Hearth Well" mean?

### ISSUE THREAD

**Issue by xfl03** [wolforcept/hearthwell#40]
When translate this mod, its name make me confused. What does the name "Hearth Well" mean?
Does it mean "Better Furnace"？
Looking forward to your reply.

**Comment by wolforcept** [comment]
Well, first and foremost its a Name, so it shouldnt really have a translation. But it does have a meaning. A well is where you get water, meaning Hearth Well is a mod which gives you what you need. And Hearth means home, in a cozy sort of way. Meaning Hearth Well gives you what you need without making you leave the comfortness of your home.
Bit it wouldnt really have a translation because they are two words that would never be seen together if I didnt join them when I created the name Hearth Well.

**Comment by xfl03** [comment]
Thanks a lot!
